/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness, the database, and the active run, if any. */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lists/{list}/members/{email}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whether one address is on a list
         * @description REQ-LST-MEMBER-STATE, REQ-LST-MEMBER-UNKNOWN. `unknown` is an address this list has never held. An address that left is `unsubscribed` and keeps the two times of its latest episode.
         */
        get: operations["readListMember"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lists/{list}/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Put an address on a list
         * @description REQ-LST-SUB-NEW, REQ-LST-SUB-ALREADY. Idempotent: an address already on the list answers `already` and nothing changes but the time it was last seen. `fields` carries the extras this list asks for at signup and is written on the episode this call opens.
         */
        post: operations["subscribeToList"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lists/{list}/unsubscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Take an address off a list
         * @description REQ-LST-UNSUB-EMAIL, REQ-LST-UNSUB-TOKEN. Exactly one of `email` and `token`. A token is the one the newsroom signed into that message's unsubscribe URL, and it is verified against this list. The answer says whether an open signup was closed and nothing else.
         */
        post: operations["unsubscribeFromList"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is up. 200 whatever db says: this is the liveness route the deploy waits on. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                        version: string;
                        active_run: string | null;
                        db: boolean;
                    };
                };
            };
        };
    };
    readListMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                list: string;
                email: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description What the list holds for the address */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "subscribed" | "unsubscribed" | "unknown";
                        joined_at?: string | null;
                        left_at?: string | null;
                    };
                };
            };
            /** @description Request failed validation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        detail: string;
                    };
                };
            };
            /** @description No usable bearer token was presented */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        detail: string;
                    };
                };
            };
            /** @description The token presented may not touch this list */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        detail: string;
                    };
                };
            };
            /** @description No such resource */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        detail: string;
                    };
                };
            };
        };
    };
    subscribeToList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                list: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    email: string;
                    fields?: {
                        [key: string]: string | number | boolean;
                    };
                };
            };
        };
        responses: {
            /** @description The address is on the list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "subscribed" | "already";
                    };
                };
            };
            /** @description Request failed validation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        detail: string;
                    };
                };
            };
            /** @description No usable bearer token was presented */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        detail: string;
                    };
                };
            };
            /** @description The token presented may not touch this list */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        detail: string;
                    };
                };
            };
            /** @description No such resource */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        detail: string;
                    };
                };
            };
        };
    };
    unsubscribeFromList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                list: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    email?: string;
                    token?: string;
                };
            };
        };
        responses: {
            /** @description The address is off the list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "removed" | "unknown";
                    };
                };
            };
            /** @description Request failed validation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        detail: string;
                    };
                };
            };
            /** @description No usable bearer token was presented */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        detail: string;
                    };
                };
            };
            /** @description The token presented may not touch this list */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        detail: string;
                    };
                };
            };
            /** @description No such resource */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        detail: string;
                    };
                };
            };
        };
    };
}
